- name: "1&1"
  url: "http://www.1and1.com/web-hosting#info-list"
  php55: 20
  php56: ??-beta
  default: 5.5.20

- name: "34SP"
  url: "https://www.34sp.com/professional-hosting-specifications"
  php53: ??
  php54: ??
  default: 5.3.??

- name: "Bluehost (shared)"
  url: "http://www.bluehost.com/shared"
  php52: ??
  php53: ??
  php54: ??
  default: 5.4.??

- name: "Crucial (Split Shared)"
  url: http://www.crucialwebhost.com/hosting/split-shared/
  php53: 29
  php54: 36
  php55: 20
  php56: 4
  default: 5.3.29

- name: "Cyon"
  url: "https://www.cyon.ch"
  php54: 34
  php55: 18
  php56: 2
  default: 5.5.18

- name: "Dreamhost"
  url: "http://www.dreamhost.com/hosting/shared/"
  php53: 27
  php54: 20
  php55: 17
  php56: 0
  default: 5.4.20

- name: "Gandi (Simple Hosting)"
  url: "https://www.gandi.net/hebergement/simple?language=php&db=mysql"
  php54: 35
  default: 5.4.35

- name: "GoDaddy (cPanel for Linux)"
  url: "https://www.godaddy.com/hosting/web-hosting.aspx?isc=hos1gbr21&ci=9009"
  php53: ??
  php54: ??
  php55: ??
  default: 5.5.??
  manual_update: Yes

- name: "Google App Engine"
  url: "https://cloud.google.com/appengine/"
  php54: 32
  default: 5.4.32
  auto_update: Yes

- name: "Heart Internet"
  url: "https://www.heartinternet.uk/web-hosting"
  php52: 17
  php53: 28
  php54: 25
  php55: 9
  default: 5.3.28
  manual_update: Yes
  auto_update: No

- name: "Heroku"
  url: "https://devcenter.heroku.com/articles/php-support#php-runtimes"
  php55: 20
  php56: 4
  default: 5.6.4
  manual_update: Yes

- name: "Hetzner"
  url: "http://www.hetzner.de"
  php52: 17
  php53: 29
  php54: 36
  php55: 20
  default: 5.3.29

- name: "HostEurope"
  url: "https://www.hosteurope.de/en/"
  php53: 29
  php54: 36
  default: 5.3.29

- name: "HostGator (shared)"
  url: "http://www.hostgator.com/shared"
  php52: 17
  php53: 28
  php54: 35
  php55: 19
  default: 5.4.35
  auto_update: Yes

- name: "Hostmonster"
  url: "https://www.hostmonster.com/"
  php52: ??
  php54: ??
  default: 5.4.??

- name: LexiConn
  url: "http://www.lexiconn.com/"
  php52: 17
  php53: 28
  php54: 35
  php55: 20
  default: 5.5.20
  manual_update: Yes
  auto_update: Yes

- name: Liquidweb
  url: "https://www.liquidweb.com"
  php52: ??
  php53: ??
  php54: ??
  php55: ??
  default: 5.5.18
  manual_update: ??
  auto_update: ??

- name: "Locaweb (shared)"
  url: "http://www.locaweb.com.br/produtos/hospedagem-de-sites/planos.html"
  php52: ??
  php53: ??
  php54: ??
  php55: ??
  php56: ??
  default: 5.2.??
  manual_update: Yes

- name: "Lunarpages (shared)"
  url: "https://support.lunarpages.com/knowledge_bases/article/326?fallback=true"
  php53: 27
  default: 5.3.27
  manual_update: No

- name: "MediaTemple (GS)"
  url: "http://mediatemple.net/webhosting/shared/"
  php53: 29
  php55: 18
  default: 5.3.29

- name: "Microsoft Azure Web Sites"
  url: "http://azure.microsoft.com/en-us/services/websites"
  php53: 29
  php54: 34
  php55: 18
  default: 5.4.34
  manual_update: Yes

- name: "Namecheap"
  url: "https://www.namecheap.com/hosting/shared.aspx"
  php52: ??
  php53: ??
  php54: ??
  php55: ??
  default: 5.3.??

- name: "names.co.uk"
  url: "https://www.names.co.uk/web-hosting/"
  php54: 35
  php55: 19
  php56: 3
  default: 5.5.19
  manual_update: Yes (Minor)
  auto_update: Yes (Patch)

- name: "OVH"
  url: "https://www.ovh.ie/web-hosting/"
  php52: 17
  php53: 29
  php54: 34
  php55: 18
  php56: 2
  default: 5.4.34
  manual_update: Yes (Minor)
  auto_update: Yes (Patch)

- name: "Rackspace (Cloud Sites)"
  url: "http://www.rackspace.com/cloud/sites"
  php53: 20
  php54: 10
  default: 5.3.20
  manual_update: Yes (Minor)
  auto_update: Yes (Patch)

- name: "Register365"
  url: "https://www.register365.com/web-hosting/"
  php54: 35
  php55: 19
  php56: 3
  default: 5.5.19
  manual_update: Yes (Minor)
  auto_update: Yes (Patch)

- name: "Pagoda Box"
  url: "https://pagodabox.com/"
  php52: 17
  php53: 23
  php54: 14
  default: 5.3.23

- name: "PCextreme"
  url: "https://www.pcextreme.nl/en/webhosting/classic"
  php53: 10
  php55: 9
  default: 5.5.9
  manual_update: Yes
  auto_update: No

- name: "ServerGrove"
  url: "http://servergrove.com/sharedhosting"
  php52: ??
  php53: 29
  php54: ??
  php55: 16
  default: 5.5.16

- name: "Site5"
  url: "http://www.site5.com/hosting/web/#programming_languages"
  php52: 17
  php53: 29
  php54: 35
  default: 5.3.29

- name: "STRATO"
  url: "http://www.strato.de"
  php53: 29
  php55: 18
  php56: 2
  default: 5.3.29

- name: "Uberspace.de"
  url: "https://uberspace.de/"
  php52: 17
  php53: 29
  php54: 35
  php55: 19
  php56: 3
  default: ??
  manual_update: No
  auto_update: Yes

- name: "VidaHost (Shared Cloud)"
  url: "https://www.vidahost.com/cloud-web-hosting"
  php52: 6
  php53: 28
  php54: 28
  php55: 12
  default: 5.3.28

- name: "WebFaction"
  url: "https://www.webfaction.com"
  php52: 17
  php53: 27
  php54: 17
  php55: 7
  default: 5.2.17
